site_name: WWDC Lounges
#site_url: https://example.com/
use_directory_urls: false

nav:
   - Welcome: index.md
   - WWDC 21:
        - SwiftUI: wwdc21/SwiftUI.md
        - A11y: wwdc21/a11y.md
        - DevTools: wwdc21/DevTools.md
   - WWDC 22:
        - swiftui: wwdc22/swiftui-lounge.md
        - devtools and swift: wwdc22/devtools-and-swift-lounge.md
        - L10n & i18n: wwdc22/localization-and-internationalization-lounge.md
        - watchos: wwdc22/watchos-lounge.md
        - uiframeworks: wwdc22/uiframeworks-lounge.md
        - graphics and games: wwdc22/graphics-and-games-lounge.md
        - object capture and room plan: wwdc22/object-capture-and-room-plan-lounge.md
        - photos camera: wwdc22/photos-camera-lounge.md
        - accessibility: wwdc22/accessibility-lounge.md
        - arkit realitykit: wwdc22/arkit-realitykit-usdz-lounge.md
        - audio and video: wwdc22/audio-and-video-lounge.md
        - design: wwdc22/design-lounge.md
        - app clips: wwdc22/app-clips-lounge.md
        - app store: wwdc22/app-store-lounge.md
        - cloudkit: wwdc22/cloudkit-lounge.md
        - coredata: wwdc22/coredata-lounge.md
        - device management: wwdc22/device-management-lounge.md
        - education: wwdc22/education-lounge.md
        - health and fitness: wwdc22/health-and-fitness-lounge.md
        - machine learning: wwdc22/machine-learning-lounge.md
        - maps: wwdc22/maps-lounge.md
        - privacy and security: wwdc22/privacy-and-security-lounge.md
        - safari: wwdc22/safari-lounge.md
        - sirikit and shortcuts: wwdc22/sirikit-and-shortcuts-lounge.md
        - widgetkit: wwdc22/widgetkit-lounge.md
   
plugins:
  - search

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  features:
    - search.share
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: cyan
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: cyan
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
- css/app.css
